version: '3.8'

services:
  # Backend API service
  backend:
    build: ./backend
    container_name: events-backend
    env_file:
      - ./backend/.env
    environment:
      - BASE_URL=https://unl-events.duckdns.org
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend:/app
      - uploads_data:/app/app/static/uploads
    depends_on:
      - db
    networks:
      - app_network
  
  # Frontend service
  frontend:
    build: ./frontend_v2
    container_name: events-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://unl-events.duckdns.org/api
    depends_on:
      - backend
    restart: always
  
  # Database service
  db:
    image: postgres:15
    container_name: events-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=events_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

# Define volumes
volumes:
  postgres_data:
  uploads_data:  # For persisting uploads

# Define networks
networks:
  app_network:
    driver: bridge 