services:
  # Backend API service
  backend:
    build: ./backend
    container_name: events-backend
    env_file:
      - ./backend/.env
    environment:
      - BASE_URL=https://unl-events.duckdns.org
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/events_db
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=events_db
    ports:
      - "8001:8000"  # Изменили порт чтобы не конфликтовать с PC Configurator
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - uploads_data:/app/static/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service
  frontend:
    build: ./frontend_v2
    container_name: events-frontend
    ports:
      - "3001:3000"  # Изменили порт чтобы не конфликтовать с PC Configurator
    environment:
      - NEXT_PUBLIC_API_URL=https://unl-events.duckdns.org/api
      - NODE_ENV=production
    depends_on:
      - backend
    restart: always

# Define volumes
volumes:
  uploads_data:  # For persisting uploads