version: '3.8'

services:
  # Backend API service
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - uploads_data:/app/app/static/uploads
    depends_on:
      - db
    networks:
      - app_network
  
  # Frontend service
  # frontend:
  #   build: ./frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:8000
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - backend
  #   networks:
  #     - app_network
  
  # Database service
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=events_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

# Define volumes
volumes:
  postgres_data:
  uploads_data:  # For persisting uploads

# Define networks
networks:
  app_network:
    driver: bridge 